### PR TITLE
Added commands

### PR DESCRIPTION
**Pull request by nwaxiomatic**
\qwa and \cwa for arrow wires

\cds for inserting … indicating general circuit

\sgate for creating gates split over non-adjacent rows

\metersymb is a new meter aesthetic

\meterB allows for a measurement operator to be added

\smeterB allows for split meters over non-adjacent rows

\cctrl allows for classical control

\inputgroups for allowing multiple rows to represent one state

### CODE REVIEW

**Comment by nwaxiomatic** [comment]
Let me know if examples are useful/necessary

**Comment by i2000s** [comment]
Thank you for contributing! Could you add in the new command demons in the `Qtutorial.tex` file? I think @Travis-S will take a closer look once this is done.

**Comment by nwaxiomatic** [comment]
Should I add one new circuit per addition?

**Comment by nwaxiomatic** [comment]
oh, I see how its setup -_-

**Comment by i2000s** [comment]
Generally if would be nice if you can add some examples on the related sections in the main text and also summarize the commands in the last appendix. People will see if the new commands are necessary or can be simplified. Thanks.

**Comment by Travis-S** [comment]
Seconding @i2000s' thoughts here.

There are three changes I would suggest before this PR should be accepted, all of them revolving around documenting the new commands in the `Qtutorial.tex` file. In particular:

* For the meters you introduce `\metersymb`, `\meterB`, and `\smeterB`, the table in section V B ("Measurements and classical bits") should be updated.

* Explain the new `\cctrl` command in section V D ("How to control anything")

* The `inputgroup` command should be documented in IV D ("Labeling input and output states")

If those changes are made and I am able to recompile the tutorial on my laptop, I think that would be a sufficient "test" to merit pulling in those changes.

Out of curiosity, what led you to require these new commands in your own work?

**Comment by nwaxiomatic** [comment]
Adding documentation now

I needed these to do the homework from Kitaev's Ph135c course in 2013. Just thought I should add these when I saw there was now a GitHub repo

**Comment by Travis-S** [comment]
Cool! Glad qcircuit was helpful. As you can see, the project has gone a bit stale. I do wonder what people use these days for drawing quantum circuits...or maybe the field has simply moved away from doing so!

**Comment by nwaxiomatic** [comment]
Yeah at the time there was basically only qcircuit, but it seemed like most people had modified it for personal use or crated their own tex library based on the circuits I was seeing.

Hopefully a public repo will help to standardize that slowly.

**Comment by nwaxiomatic** [comment]
Let me know if the updated tutorial is ok, hopefully no typos

**Comment by Travis-S** [comment]
I will review this tonight (have to figure out how to do PR through the command line). Assuming the tutorial compiles and the new commands are documented reasonably well, I will merge.

**Comment by Travis-S** [comment]
This PR was closed, incorporating the changes proposed by @nwaxiomatic, with the addition of more documentation in the `Qtutorial.tex` file above those initially made.

**Pull request merged**
